#!/usr/bin/env python3
"""Download Google Fonts assets used by design.html into ./fonts and emit ./fonts.css.

Run from project root:
    python3 scripts/fetch-fonts.py

Hits the Google Fonts CSS2 endpoint with a modern Chrome User-Agent so we get
woff2 + unicode-range subsetting (small per-file, browser only loads what it
needs). All referenced woff2 files are mirrored under ./fonts/ and the rewritten
CSS lands at ./fonts.css with relative URLs. Re-running is idempotent — files
already on disk are skipped.
"""
import os
import re
import sys
import time
import urllib.error
import urllib.request
import pathlib

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36"
)

FAMILIES = [
    "ZCOOL+XiaoWei",
    "Noto+Serif+SC:wght@400;600;800;900",
    "IM+Fell+English+SC",
    "IM+Fell+English:ital@0;1",
    "Special+Elite",
    "Ma+Shan+Zheng",
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "fonts"
CSS_OUT = ROOT / "fonts.css"


def fetch(url: str, retries: int = 4) -> bytes:
    last_err: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=45) as r:
                return r.read()
        except (urllib.error.URLError, TimeoutError, ConnectionError) as e:
            last_err = e
            wait = 1.5 * attempt
            print(f"  retry {attempt}/{retries} after {wait:.1f}s ({e})", file=sys.stderr)
            time.sleep(wait)
    raise RuntimeError(f"giving up on {url}: {last_err}")


def main() -> int:
    FONTS_DIR.mkdir(exist_ok=True)
    css_chunks = []
    for fam in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?family={fam}&display=swap"
        print(f"[css ] {fam}", file=sys.stderr)
        css_chunks.append(f"/* === {fam} === */\n" + fetch(url).decode("utf-8"))
    combined = "\n\n".join(css_chunks)

    seen = set()

    def repl(match: "re.Match[str]") -> str:
        url = match.group(1)
        name = url.rsplit("/", 1)[-1]
        local = FONTS_DIR / name
        if name not in seen:
            seen.add(name)
            if not local.exists():
                print(f"[font] {name}", file=sys.stderr)
                local.write_bytes(fetch(url))
        return f"url(./fonts/{name})"

    rewritten = re.sub(r"url\((https://[^)]+\.woff2)\)", repl, combined)

    header = (
        "/* Generated by scripts/fetch-fonts.py — do not edit by hand.\n"
        "   Source: fonts.googleapis.com/css2 (Google Fonts).\n"
        "   Re-run the script to refresh font assets. */\n\n"
    )
    CSS_OUT.write_text(header + rewritten, encoding="utf-8")
    print(f"\nWrote {CSS_OUT.relative_to(ROOT)}  ({len(seen)} woff2 files)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
